config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    
    resources :customers,only: []
     get'customers' => 'customers#show'
     get'customers/edit' => 'customers#edit'
     get'customers/quit' => 'customers#quit'
     patch'customers/out' => 'customers#out'
     patch 'update/customers' => 'customers#update'
    resources :addresses
    resources :items
    resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanx'
        end
      end
  end
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

   namespace :admin do
     
    get 'homes/top'
    
    
    resources :admin
    resources :genres
    resources :items
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  	validates :customer_id, :name, :address, presence: true
  	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  	
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
	validates :customer_id, :item_id, :amount, presence: true
  validates :amount, numericality: { only_integer: true }
  
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy       
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def kana_full_name
    kana_last_name + " " + kana_first_name
  end
         
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, uniqueness: true, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_many :orders
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def add_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many :order_details, dependent: :destroy

	validates :customer_id, presence: true
	validates:address, presence: true
	validates:name, presence: true
	validates:shipping_cost,presence: true
	validates:total_payment, presence: true
	validates:payment_method,presence: true
			  		
			  		
  def sum_of_price
    item.add_tax_price * amount
  end  
	

enum payment_method: { credit_card: 0, transfer: 1 }
enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
	belongs_to :item
	
	validates :item_id, :order_id, :amount, :price, presence: true
	validates :price, :amount, numericality: { only_integer: true }
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end
   
  private
   def customer_params
     params.require(:customer).permit(
       :first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:phone_number,:email,:is_deleted)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品の新規登録内容に不備があります。"
      render :new
    end
    
  end
  
  def update
     @item = Item.find(params[:id])
     if @item.update(item_params)
       flash[:notice] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash[:alert] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end
  
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price,:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
     private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
      else
        customers_path
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      if  resource_or_scope == :admin
        new_admin_session_path
      else
        new_customer_session_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<% provide(:title, "会員情報編集") %>
<div class="container">
  <h2 class="text-center m-5"><%= @customer.full_name%>さんの会員情報編集</h2>
  <div class="row d-flex justify-content-center">
    
  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <div class="col-xs-10 offset-1">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID", class: "col-sm-4" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"氏名", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 form-control-static" %>　
        <%= f.text_field :first_name, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :kana_last_name, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :kana_first_name, class: "col-sm-3 form-control-static name" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"郵便番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :postal_code, class: "col-sm-3" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"住所", class: "col-sm-4 control-label" %>
        <%= f.text_field :address, class: "col-sm-7" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"電話番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :phone_number, class: "col-sm-4" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効"%>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会" %>
      </div>
    </div>
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
        <%= link_to '会員詳細画面へ戻る',admin_customer_path, class:"btn btn-outline-secondary"%>
      </div>

  <% end %>
    
  </div>
</div>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table class="table">
      <thead>
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
      </thead>
        
      <tbody>
        <% @customers.each do |customer| %>
         <tr>
             <td class="info col-xs-1">
                <%= customer.id %>
             </td>
             <td class="text-left">
                <%= link_to customer.full_name,admin_customer_path(customer) %>
             </td>
             <td class="text-left">
                <%= customer.email %>
             </td>
             <td class="col-xs-2">
                <% if customer.is_deleted == true%>
                  <p class="text-secondary">退会済</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
             </td>
         </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/customers/show.html.erb
<h1>会員情報詳細</h1>
<table>
            <tr>
              <th>会員ID</th>
              <td><%= @customer.id%></td>
            </tr>
            <tr>
              <th>氏名</th>
              <td><%= @customer.full_name%></td>
            </tr>
            <tr>
              <th>フリガナ</th>
              <td><%= @customer.kana_full_name%></td>
            </tr>
            <tr>
              <th>郵便番号</th>
              <td><%= @customer.postal_code%></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= @customer.address%></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= @customer.phone_number%></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= @customer.email%></td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <% if @customer.is_deleted == true%>
               <td>退会済み</td>
              <% else %>
               <td>有効</td>
              <% end %>
            </tr>            
          </table>
          <div>
            <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success"%></p>
            <p><%= link_to "注文履歴一覧を見る",admin_homes_top_path, class:"btn btn-primary"%></p>
          </div>