config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    
    resources :customers,only: []
     get'customers' => 'customers#show'
     get'customers/edit' => 'customers#edit'
     get'customers/quit' => 'customers#quit'
     patch'customers/out' => 'customers#out'
     patch 'update/customers' => 'customers#update'
    resources :addresses
    resources :items
    resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanx'
        end
      end
  end
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

   namespace :admin do
     
    get 'homes/top'
    
    
    resources :admin
    resources :genres
    resources :items
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  	validates :customer_id, :name, :address, presence: true
  	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  	
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
	validates :customer_id, :item_id, :amount, presence: true
  validates :amount, numericality: { only_integer: true }
  
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy       
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def kana_full_name
    kana_last_name + " " + kana_first_name
  end
         
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, uniqueness: true, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_many :orders
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def add_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many :order_details, dependent: :destroy

	validates :customer_id, presence: true
	validates:address, presence: true
	validates:name, presence: true
	validates:shipping_cost,presence: true
	validates:total_payment, presence: true
	validates:payment_method,presence: true
			  		
			  		
  def sum_of_price
    item.add_tax_price * amount
  end  
	

enum payment_method: { credit_card: 0, transfer: 1 }
enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
	belongs_to :item
	
	validates :item_id, :order_id, :amount, :price, presence: true
	validates :price, :amount, numericality: { only_integer: true }
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
    else
      flash[:alert] = "変更内容に不備があります。"
      render "edit"
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品の新規登録内容に不備があります。"
      render :new
    end
    
  end
  
  def update
     @item = Item.find(params[:id])
     if @item.update(item_params)
       flash[:notice] = "商品詳細の変更が完了しました。"
       redirect_to admin_item_path(@item)
     else
       flash[:alert] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
  end
  
  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price,:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
     private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
      else
        customers_path
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      if  resource_or_scope == :admin
        new_admin_session_path
      else
        new_customer_session_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>
<%= form_with model: @genre,url: admin_genre_path, method: :patch, local: true do |f| %>
  <div class="form-group">
    <%= f.label "ジャンル名" %>
    <%= f.text_field :name %>
  </div>
  <div class = "btn btn-outline-secondary btn-block">
    <%=f.submit "変更を保存" %>
  </div>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>
<%= form_with model: @genre,url: admin_genres_path,method: :post, remote: true do |f| %>
    <%= f.label :name, "ジャンル名" %>
    <%= f.text_field :name, id: "form" %>
    <%= f.submit "新規登録" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th></th> 
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<div>
    <div>
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
        <tr>
          <div>
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </div>
        </tr>
        <tr>
          <div>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div>
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div>
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </div>
        </tr>
        <tr>
        <div>
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div>
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
          </td>
        </div>
        </tr>
        <tr>
        <div>
          <th><%= f.submit "変更を保存" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
      <table>
        <thread>
            <tr>
             <th>商品ID</th>
             <th>商品名</th>
             <th>税抜価格</th>
             <th>ジャンル</th>
             <th>ステータス</th>
            </tr>
         </thread>
        <tbody>
         <% @items.each do |item| %>
         <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name,admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
              <p class="text-success ">販売中</p>
             <% else %>
              <p class="text-secondary ">販売停止中</p>
            <% end %>
          </td>
         </tr>
        <% end %>
        </tbody>
    </table>
    <%= link_to '新規作成', new_admin_item_path %>

app/views/admin/items/new.html.erb
<h1>商品新規登録画面</h1>
<div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
          </td>
        </div>
        </tr>
        <tr>
        <div class="form-action">
          <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<%= image_tag @item.image %>

<table>
  <tr>
  　<th>商品名</th>
    <td><%= @item.name %></td>
　</tr>
  <tr>
    <th>商品説明</th>
    <td><%= @item.introduction %></td>
  </tr>
  <tr>
  　<th>ジャンル</th>
    <td><%= @item.genre.name %></td>
  </tr>
  <tr>
    <th>
      税込価格<br>
      (税抜き価格)
    </th>
  　<td><%= @item.add_tax_price %> (<%= @item.price %>) 円</td>
  </tr>
  <tr>
   <th>販売ステータス</th>
  <td>
    <% if @item.is_active == true %>
    　<p>販売中</p>
    <% else %>
      <p>販売停止中</p>
    <% end %>
  </td>
　</tr>
</table>


<div>
  <p><%= link_to '編集する', edit_admin_item_path %></p>
</div>