config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...

  scope module: :public do
    root to: "homes#top"
    get 'homes/about'
    
    resources :customers,only: []
     get'customers' => 'customers#show'
     get'customers/edit' => 'customers#edit'
     get'customers/quit' => 'customers#quit'
     patch'customers/out' => 'customers#out'
     patch 'update/customers' => 'customers#update'
    resources :addresses
    resources :items
    resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanx'
        end
      end
  end
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

   namespace :admin do
     
    get 'homes/top'
    
    
    resources :admin
    resources :genres
    resources :items
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  	validates :customer_id, :name, :address, presence: true
  	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  	
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
	validates :customer_id, :item_id, :amount, presence: true
  validates :amount, numericality: { only_integer: true }
  
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy       
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def kana_full_name
    kana_last_name + " " + kana_first_name
  end
         
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, uniqueness: true, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_many :orders
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def add_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
	has_many :order_details, dependent: :destroy

	validates :customer_id, presence: true
	validates:address, presence: true
	validates:name, presence: true
	validates:shipping_cost,presence: true
	validates:total_payment, presence: true
	validates:payment_method,presence: true
			  		
			  		
  def sum_of_price
    item.add_tax_price * amount
  end  
	

enum payment_method: { credit_card: 0, transfer: 1 }
enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
	belongs_to :item
	
	validates :item_id, :order_id, :amount, :price, presence: true
	validates :price, :amount, numericality: { only_integer: true }
	enum making_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
     private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_homes_top_path
      else
        customers_path
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      if  resource_or_scope == :admin
        new_admin_session_path
      else
        new_customer_session_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <% if admin_signed_in? %>
        <%= link_to "NaganoCAKE", admin_orders_path, class:"header-title navbar-brand"%>
      <% else %>
        <%= link_to "NaganoCAKE", root_path, class:"header-title navbar-brand"%>
      <% end %>

      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <% if customer_signed_in? %>
          <li class="nav-item active">
           <span class="nav-link text-dark">ようこそ<%= current_customer.full_name %>さん</span>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", customers_path(current_customer), class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>
          <li class="nav-item ">
            <%= link_to "商品一覧", items_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "カート",cart_items_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_items_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_homes_top_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト",destroy_admin_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
         <% else %>
         <li class="nav-item">
             <%= link_to "about", homes_about_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", items_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_customer_session_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
          <% end %>
        </ul>
      </div>

 </nav>
</header>
  

  <body>
    <%= yield %>
  </body>
</html>